### ISSUE TITLE
Support uploading to flash

### ISSUE THREAD

**Issue by thejpster** [evq/atsaml11xxx#1]
I'm going to try and replicate your setup later. What issues have you seen trying to write to flash? Do you think it's TrustZone related?

**Comment by evq** [comment]
It has been some time since I tried - looks like [edbg](https://github.com/ataradov/edbg) has added support for flashing the SAM L11. :heart: 

I tested and added instructions to the README / changed the default link script to target flash in ef8ea3ae8f1265c11d2ca9a4ddcd9f4c0a176d4f.

I think the difficulty in writing to flash on this particular chip is that it requires first putting the boot rom into interactive mode, I wasn't able to get that far when I was last messing around.

edit: might be that only chip erase that requires bootrom. I think I thought my DAL value meant I needed to do an erase first
